# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tag', to='posts.Post'),
        ),
    ]
